package com.breathe.breatheApi.enums;

public enum Location {
    LOWLINE_SLACKLINE_PARK,
    HIGHLINE_FOREST,
    CLOTHING_SWAP,
    COLLECTIVE_ALTAR,
    COMMUNITY_MEAL_TENT,
    PEAK_TO_PEAK_SLACKLINE_PARK,
    ENSOUL_MUSIC_BARN,
    THE_COURT,
    FIRE_SPINNING_DESIGNATED_AREA,
    MOVEMENT_TENT,
    TALK_TENT,
    DIVERSITY_AND_INCLUSION_TENT,
    SPEAK_SPACE,
    INNER_SENSE_TENT,
    LOUNGE,
    LITTLE_BREATHERS_TENT,
    PARTY_POND,
    VAN_LIFE,
    BALANCING_EARTH_SLACKLINE_PARK,
    FIRE_PIT,
    IDIOPAN_STAGE,
    BALANCE_COMMUNITY_POND,
    MEET_UP_SPOT,

}
